# Generated by Django 5.0.7 on 2024-07-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
