# Generated by Django 5.0.7 on 2024-07-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_libro_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
